# Generated by Django 3.2.7 on 2021-10-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilet', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='employment',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
