# Generated by Django 3.2.7 on 2021-10-09 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilet', '0003_auto_20211009_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='employment',
        ),
    ]
