# Generated by Django 3.2.7 on 2021-10-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilet', '0004_remove_profile_employment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employment',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
