# Generated by Django 3.2.7 on 2021-10-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilet', '0005_profile_employment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='employment',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
