# Generated by Django 3.2.8 on 2021-10-12 18:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bilet', '0007_alter_profile_country'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proposal',
            new_name='Offer',
        ),
    ]
