# Generated by Django 3.2.8 on 2021-10-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilet', '0008_rename_proposal_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='subjectproposal',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='handlingid',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='typerecordid',
        ),
        migrations.AddField(
            model_name='offer',
            name='subject',
            field=models.CharField(default='Как жить дальше!!!', max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='file',
            field=models.ImageField(upload_to='offer'),
        ),
    ]
