# Generated by Django 3.2.8 on 2021-10-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilet', '0009_auto_20211013_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='audiooffer',
            field=models.CharField(default='ФАЙЛ', max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='address',
            field=models.CharField(default='Бишкек', max_length=50),
        ),
    ]
