# Generated by Django 3.2.8 on 2021-10-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilet', '0010_auto_20211013_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='file',
            field=models.FileField(upload_to='offer/'),
        ),
    ]
