# Generated by Django 3.2.8 on 2021-10-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilet', '0011_alter_offer_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='file',
            new_name='files',
        ),
    ]
