# Generated by Django 3.2.8 on 2021-10-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilet', '0012_rename_file_offer_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='offer/'),
        ),
    ]
